server.port = 8080

spring.datasource.url=jdbc:mysql://localhost:3306/iriro_db

spring.datasource.username=root
spring.datasource.password=1234

#spring.jpa.hibernate.ddl-auto = update
spring.jpa.hibernate.ddl-auto = create


# 개발 단계 디버깅(확인용)
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
logging.level.org.hibernate.jdbc.bind = TRACE
logging.level.org.hibernate.sql = DEBUG

spring.sql.init.mode = always
spring.sql.init.data-locations=classpath:/sql/data.sql
spring.jpa.defer-datasource-initialization = true

#Tmap API key
tmap.app-key=WUBHwX9D0v7A2ynMvipAb7rC3Z6ErEgf4iLHqw3Z
tmap.pedestrian-url=https://apis.openapi.sk.com/tmap/routes/pedestrian?version=1

#pub API key
api.pub.service-key=b9c001aab838aaf168743c5eea9b492c8651a999fc31922d4edbd67c95035ea5
api.pub.crime-road.url=https://apis.data.go.kr/1383000/sais/SexualAbuseNoticeAddrService
api.pub.safe-house.url=http://api.data.go.kr/openapi/tn_pubr_public_female_safety_prtchouse_api
api.admin.service-key=L59Y0SCX-L59Y-L59Y-L59Y-L59Y0SCX4Q
api.admin.safe-fac=https://safemap.go.kr/openapi2/IF_0036
api.seoul.service-key=66666d56446c656533386572676756
api.seoul.safe-house.url=https://api.data.go.kr/openapi/tn_pubr_public_female_safety_prtchouse_api